ParseFromString expects string not bytearray
Fixes bug introduced in e4aebdb.

Added regression test, before it was failing with:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/adam/workspace/smk_python_sdk/smarkets/tests/streaming_api/session.py", line 12, in test_next_frame_regression
    payload = session.next_frame()
  File "/home/adam/workspace/smk_python_sdk/smarkets/streaming_api/session.py", line 168, in next_frame
    payload.ParseFromString((data))
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 1093, in MergeFromString
    raise message_mod.DecodeError('Truncated message.')
DecodeError: Truncated message.